### ISSUE TITLE
Cellspacer.py help isn't

### ISSUE THREAD

**Issue by stucka** [PalmBeachPost/postgeo#13]
C:\data\postgeo>cellspacer.py
usage: cellspacer.py [-h] [-v] [-m M] filename
cellspacer.py: error: too few arguments

**Comment by michealbeatty** [comment]
Not understanding this one. Are you running cellspacer.py without specifying a filename to transform?

**Comment by stucka** [comment]
Yep. Is there any way we can get cellspacer.py with no options to show the output of cellspacer.py -h ?

**Comment by michealbeatty** [comment]
Good question. Let me look into it.

**Comment by stucka** [comment]
PRetty sure you fixed this months back.
