### ISSUE TITLE
cellspacer.py fails in verbose mode

### ISSUE THREAD

**Issue by michealbeatty** [PalmBeachPost/postgeo#4]
In the condition where value == flagonsolo and verbose == 1, cellspacer.py fails because the print statement references the bearing variable before it has a value assigned to it. bearing only has a value assigned to it when value is not equal to flagonsolo.
This should be an easy fix by adding a generic assignment to bearing in condition where value == flagonsolo such as bearing = "N/A"

**Comment by stucka** [comment]
Fixed by earlier @amikiri update. Changed to -1 just because I never feel comfortable with Python shifting types. =)
